version: "3"
services:
  app:
    container_name: deno-demo-app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/usr/local/app
    tty: true
    ports:
      - 3000:3000
